### ISSUE TITLE
Should the volunteer have a specific certification that proves its status, or is the status just an information stored on the DB? => TBD g0v Core team?

### ISSUE THREAD

**Issue by ecow** [safe-together/specification#17]

**Comment by luca** [comment]
I have put some thoughts on this and it might be either ways, but in any case the system would require to maintain some capability to handle offline, non-app-supported use cases.

Given that the target here is to empower volunteers to support the fragile population, we should try to accomodate situations where the recipient of the support action doesn't have a smartphone or other technological aide.

What is the goal of the certification? Why should someone get the status certification?

It's my understanding that the main goal of the volunteer certification is

**to help the fragile people feel safe when getting help**

what are the risks they need to be safe from?

- getting infected from COVID-19 by well intentioned people trying to help
- opening their house to ill-intentioned people (who misrepresent themselves as being part of the volunteers)

The fragile population should therefore have **an easy way to identify the person coming to their house as being non-infectious and part of the support operations**.

The **certification** should help supporting this. So it:

1. should be created/validated by medical personnel
2. should not be forgeable
3. should be tied to the person
4. should enable verification at safe-distance

**Comment by ecow** [comment]
volunteers are not the only target of the shielding system. See also  https://safe-together.github.io/specification/stories/#US15  . We could imagine that the same (or similar) app used by the fragile people can be used by anyone that requires to check someone's immunity.

**Comment by ecow** [comment]
Discussione con Federico di Infocert
